tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "gnupg"
brew "pinentry-mac"
brew "d12frosted/emacs-plus/emacs-plus", args: ["HEAD", "with-debug", "with-emacs-27-branch", "with-jansson", "with-modern-icon", "with-no-frame-refocus", "with-no-titlebar", "with-xwidgets"]
cask "discord"
cask "hammerspoon"
cask "karabiner-elements"
